### ISSUE TITLE
Unit test support

### ISSUE THREAD

**Issue by nav-github01001** [EpikCord/EpikCord.py#163] opened 2022-06-19 10:29 UTC
### Summary

^

### The Problem

It allows us to check if something is wrong (like parsing data in any function os wrong so that it may be easier

### The Ideal Solution

Doit

### The Current Solution

Users have to manually test themselves after the library is released. Adding unittests could be useful as it mays solve any thing b4 releasing the lib

**Comment by EmreTech** [comment] 2022-09-12 03:46
Duplicate of #195

**Closed** 2022-09-12 14:35 UTC
Labels: enhancement
